/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>   // Standard integer types (uint8_t, uint32_t, etc.)
#include "gpio.h"     // Your custom GPIO driver for LED control

// Compile-time check:
// If FPU instructions are enabled but FPU is not initialized, warn developer
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// Flag to control LED state (0 = OFF sequence, 1 = ON sequence)
	uint8_t allLedOn = 0;

	// Initialize GPIO pins for LEDs (PD12–PD15)
	led_init();

	// Turn ON all LEDs initially
	green_led_on();
	orange_led_on();
	red_led_on();
	blue_led_on();

    /* Infinite loop (typical in embedded systems) */
	for(;;)
	{
		if(allLedOn)
		{
			// Sequentially turn ON LEDs with delay

			green_led_on();
			for(volatile uint32_t delay = 0; delay < 1000000; delay++); // crude delay loop

			orange_led_on();
			for(volatile uint32_t delay = 0; delay < 1000000; delay++);

			red_led_on();
			for(volatile uint32_t delay = 0; delay < 1000000; delay++);

			blue_led_on();
			for(volatile uint32_t delay = 0; delay < 1000000; delay++);
		}
		else
		{
			// Sequentially turn OFF LEDs with delay

			green_led_off();
			for(volatile uint32_t delay = 0; delay < 1000000; delay++);

			orange_led_off();
			for(volatile uint32_t delay = 0; delay < 1000000; delay++);

			red_led_off();
			for(volatile uint32_t delay = 0; delay < 1000000; delay++);

			blue_led_off();
			for(volatile uint32_t delay = 0; delay < 1000000; delay++);
		}

		// Toggle state:
		// XOR with 1 flips between 0 and 1
		allLedOn ^= 1;
	}
}
