/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define PERIPHERAL_BASE		0x40000000UL
#define AHB1PERIPH_OFFSET 	0x00020000UL
#define AHB1PERIPH_BASE 	(PERIPHERAL_BASE + AHB1PERIPH_OFFSET)
#define RCC_OFFSET			0x00003800UL
#define RCC_BASE			(AHB1PERIPH_BASE + RCC_OFFSET)
#define RCC_AHB1ENR_OFFSET  0x30UL
#define RCC_AHB1EN_R		(*(volatile uint32_t *)(RCC_BASE + RCC_AHB1ENR_OFFSET))
#define GPIOD_OFFSET		0x00000C00UL
#define GPIOD_BASE			(AHB1PERIPH_BASE + GPIOD_OFFSET)
#define GPIOD_MODER_OFFSET	0x00UL
#define GPIOD_MODE_R		(*(volatile uint32_t *)(GPIOD_BASE + GPIOD_MODER_OFFSET))
#define GPIOD_ODR_OFFSET	0x14UL
#define GPIOD_OD_R			(*(volatile uint32_t *)(GPIOD_BASE + GPIOD_ODR_OFFSET))



int main(void)
{
	/* Enable the clock for GPIOD */
	RCC_AHB1EN_R |= (1 << 3U);

	/* Output mode configuration for PD12, PD13, PD14, PD15 */
	GPIOD_MODE_R |= (1 << 24U);
	GPIOD_MODE_R &= ~(1 << 25U);
	GPIOD_MODE_R |= (1 << 26U);
	GPIOD_MODE_R &= ~(1 << 27U);
	GPIOD_MODE_R |= (1 << 28U);
	GPIOD_MODE_R &= ~(1 << 29U);
	GPIOD_MODE_R |= (1 << 30U);
	GPIOD_MODE_R &= ~(1 << 31U);

	/* Set PD12, PD13, PD14, PD15 to high */
	GPIOD_OD_R |= (1 << 12U);
	GPIOD_OD_R |= (1 << 13U);
	GPIOD_OD_R |= (1 << 14U);
	GPIOD_OD_R |= (1 << 15U);
    /* Loop forever */
	for(;;) {
		GPIOD_OD_R ^= (1 << 12U);
		for(uint32_t delay = 0; delay < 1000000; delay++);
		GPIOD_OD_R ^= (1 << 13U);
		for(uint32_t delay = 0; delay < 1000000; delay++);
		GPIOD_OD_R ^= (1 << 14U);
		for(uint32_t delay = 0; delay < 1000000; delay++);
		GPIOD_OD_R ^= (1 << 15U);
		for(uint32_t delay = 0; delay < 1000000; delay++);
	}
}
