/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef struct
{
	volatile uint32_t DUMMY[12];
	volatile uint32_t AHB1ENR;
} RCC_Typedef;

typedef struct
{
	volatile uint32_t MODER;
	volatile uint32_t OTYPER;
	volatile uint32_t OSPEEDR;
	volatile uint32_t PUPDR;
	volatile uint32_t IDR;
	volatile uint32_t ODR;
	volatile uint32_t BSRR;
	volatile uint32_t LCKRR;
	volatile uint32_t AFRL;
	volatile uint32_t AFRH;
} GPIO_Typedef;

#define RCC_BASE 	0x40023800UL
#define GPIOD_BASE 	0x40020C00UL
#define RCC ((RCC_Typedef *) RCC_BASE)
#define GPIOD	((GPIO_Typedef *) GPIOD_BASE)



int main(void)
{
	/* Enable the clock for GPIOD */
	RCC->AHB1ENR |= (1 << 3U);

	/* Output mode configuration for PD12, PD13, PD14, PD15 */
	GPIOD->MODER &= ~(1 << 25U);
	GPIOD->MODER |= (1 << 24U);
	GPIOD->MODER &= ~(1 << 27U);
	GPIOD->MODER |= (1 << 26U);
	GPIOD->MODER &= ~(1 << 29U);
	GPIOD->MODER |= (1 << 28U);
	GPIOD->MODER &= ~(1 << 31U);
	GPIOD->MODER |= (1 << 30U);

	/* Set PD12, PD13, PD14, PD15 to high */
	GPIOD->ODR |= (1 << 12U);
	GPIOD->ODR |= (1 << 13U);
	GPIOD->ODR |= (1 << 14U);
	GPIOD->ODR |= (1 << 15U);
    /* Loop forever */
	for(;;) {
		GPIOD->ODR ^= (1 << 12U);
		for(uint32_t delay = 0; delay < 1000000; delay++);
		GPIOD->ODR ^= (1 << 13U);
		for(uint32_t delay = 0; delay < 1000000; delay++);
		GPIOD->ODR ^= (1 << 14U);
		for(uint32_t delay = 0; delay < 1000000; delay++);
		GPIOD->ODR ^= (1 << 15U);
		for(uint32_t delay = 0; delay < 1000000; delay++);
	}
}
